### ISSUE TITLE
ReportMethods is throwing Exception

### ISSUE THREAD

**Issue by sachin-arora** [Adobe-Marketing-Cloud/analytics-java-library#22]
I am using below code and getting NoSuchMethodError.
Code:
ReportMethods reportMethods = new ReportMethods(client);
int reportId = reportMethods.queue(desc);

Exception:
 java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.getSha1Digest()Ljava/security/MessageDigest;
	at com.adobe.granite.analytics.client.auth.WsseAuthenticator.getBase64Digest(WsseAuthenticator.java:55)
	at com.adobe.granite.analytics.client.auth.WsseAuthenticator.getHeader(WsseAuthenticator.java:33)
	at com.adobe.granite.analytics.client.auth.WsseAuthenticator.authenticate(WsseAuthenticator.java:27)
	at com.adobe.granite.analytics.client.AnalyticsClient.callMethod(AnalyticsClient.java:43)
	at com.adobe.granite.analytics.client.AnalyticsClient.callMethod(AnalyticsClient.java:31)
	at com.adobe.granite.analytics.client.methods.ReportMethods.queue(ReportMethods.java:21)

**Comment by sachin-arora** [comment]
I have found cause of this issue. It was because of DigestUtils of different Jar being used in runtime. Closing the issue.
